name = "HeartRateVariability"
uuid = "0047d930-76bf-11ea-1377-bb3cda807e9f"
authors = ["Jasmin Walter <jasmin.walter@mni.thm.de>"]
version = "1.0"

[deps]
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
LombScargle = "fc60dff9-86e7-5f2f-a8a0-edeadbb75bd9"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Trapz = "592b5752-818d-11e9-1e9a-2b8ca4a44cd1"

[compat]
Trapz = "2.0"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
